name: Redis 6.2

# Controls when the workflow will run
on:
  schedule:
    - cron: '37 3 * * 1'
  workflow_dispatch:
    inputs:
      rejsonVersion:
        type: string
        required: true
        default: "latest"
        description: "Which redis/rejson image tag to use to source rejson module"
      bitnamiRedisVersion:
        type: string
        required: true
        default: "6.2-debian-11"
        description: "Which bitnami/redis image tag to use as runtime image"
      push:
        type: boolean
        required: true
        default: false
        description: "Push image to container registry?"

# permissions are needed if pushing to ghcr.io
permissions: 
  contents: read
  packages: write

env:
  REJSON_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.rejsonVersion || 'latest' }}
  BITNAMI_REDIS_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.bitnamiRedisVersion || '6.2-debian-11' }}
  FQIN: "ghcr.io/${{ github.repository }}/redis"
  PUSH_IMAGE: ${{ github.event_name == 'workflow_dispatch' && inputs.push || true }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # https://github.com/docker/login-action
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/docker/metadata-action
      - name: Docker meta
        id: docker_meta # you'll use this in the next step
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.FQIN }}
          # Docker tags based on the following events/attributes
          tags: |
            ${{ env.BITNAMI_REDIS_VERSION }}
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./bitnami/redis/6.2/debian-11
          file: ./bitnami/redis/6.2/debian-11/Dockerfile.Rejson
          platforms: linux/amd64
          push: ${{ env.PUSH_IMAGE }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            REJSON_VERSION=${{ env.REJSON_VERSION }}
            BITNAMI_REDIS_VERSION=${{ env.BITNAMI_REDIS_VERSION }}
